// Dynare mod file for "The Mortgage Credit Channel of Macroeconomic Transmission"
// Author: Daniel L. Greenwald

// This file is automatically generated and may contain errors. 
// Please report any issues to dlg@mit.edu.

// Selected variable definitions:

// F_ltv_level: $F^{LTV}$
// cpr_level: Prepay Rate
// e_transfer: Transfer
// k_inv_rate: K Inv. Rate
// log_Om_m_borr: $\Omega_m$
// log_Om_x_borr: $\Omega_x$
// log_R_2_ann: 2Y Rate
// log_R_ann: $R_t$
// log_R_new: $R_t$
// log_R_new_100: $R_t$
// log_R_real: Real R
// log_Rm_ann: Mortgage Rate
// log_a_til: TFP
// log_c: Consumption
// log_c_hat_borr: Borr. Cons.
// log_c_hat_saver: Saver Cons.
// log_debt: Debt
// log_debt_limit: Avg. Debt Limit
// log_debt_limit_ltv: LTV Limit
// log_debt_limit_pti: PTI Limit
// log_debt_mult: $\mu_t$
// log_debt_new: Debt
// log_debt_payment: Payment
// log_dltv_dh: Collat. Eff.
// log_e_bar: Income Threshold
// log_eps_pol: Policy
// log_h_value_borr: House Price
// log_labor_inc_borr: Borr. Income
// log_lti: Average LTI
// log_ltv: Average LTV
// log_mc: Marginal Cost
// log_n_hat_borr: Borr. Hours
// log_n_hat_saver: Saver Hours
// log_pay_new: Avg. Payment
// log_ph: House Price (All)
// log_ph_borr: House Price
// log_pi: Inflation (Q)
// log_pi_ann: Inflation
// log_pi_star: Infl. Target
// log_price_rent_borr: Price-Rent Ratio
// log_pti: Average PTI
// log_q_star: Log Mort. Coupon
// log_res_inv_total: Res. Inv. (All)
// log_spend_borr: Borr. Expend.
// log_spend_saver: Saver. Expend.
// log_tv_lim_ltv: LTV Limit
// log_tv_lim_pti: PTI Limit
// log_tv_markup: Markup
// log_tv_xi: House Pref.
// log_vti: Value/Income
// log_w_saver: Wage
// log_y: Output
// ltv_gap: Issuance/Price
// ltv_new_debt: New Loan LTV
// mathcal_C: $\mathcal{C}_t$
// new_issuance: New Issuance
// pti_new_debt: New Loan PTI
// q_avg_ann_level: $q$
// q_star_ann_level: $q_t^*$
// term_premium: Term Premium
// yield_curve_slope: $\log R_{10Y} - \log R$

parameters H_borr, H_hat_bar_borr, H_hat_bar_saver, H_hat_borr, H_hat_saver, H_saver,
  H_to_inc_borr, H_to_inc_saver, alp_k, bet_bar_borr, bet_bar_saver, bet_g_bar_borr,
  bet_g_bar_nom_inv_borr, bet_g_bar_nom_inv_saver, bet_g_bar_saver, chi_borr, chi_saver,
  coeff_0, coeff_m, cpr_bar, del, dispersion_max, dispersion_min, epsi, eta, eta_borr,
  eta_saver, frac_active, frequency, g_bar, habit, init_avg_amort_diff, kap_star_bar,
  lam, log_H_hat_borr, log_H_hat_saver, log_R_bar, log_R_cal, log_R_real_bar, log_R_spread,
  log_R_til_spread, log_Rm_ann_bar, log_a_bar, log_debt_hat_bar, log_debt_limit_baseline,
  log_debt_spread, log_dispersion_max, log_dispersion_min, log_dispersion_spread,
  log_g_bar, log_mc_bar, log_pi_bar, ltv_bar, mu_foreign_debt, mu_kap, mu_log_a_til,
  mu_log_pi_star, mu_log_tv_xi, mu_term_premium, mu_tv_tax_ins, n_std, n_std_endog,
  n_std_pc, non_am_share_bar, non_am_share_nom_bar, nu_1, nu_10, nu_2, nu_bond, other_debt_frac,
  pay_spread, phi_h_adj, phi_pi, phi_y, pi_bar, psi, pti_bar, q_coeff_bar, q_tax_ins_bar,
  quiet, rho_adj, rho_foreign_debt, rho_log_a_til, rho_log_pi_star, rho_log_tv_xi,
  rho_pol, rho_term_premium, scale, scale_final, servicing_costs, sig_adj, sig_e_inc,
  sig_foreign_debt, sig_kap, sig_log_a_til, sig_log_pi_star, sig_log_tv_xi, sig_term_premium,
  tau_inc, tp_offset_1, tp_offset_2, varphi, varphi_inv, xi_bar_borr, xi_bar_saver,
  y_steady, zet;

var E_Om_m_borr, E_Om_m_saver, E_Om_pay_borr, E_Om_pay_saver, E_euler_saver, E_log_pi,
  E_p1, E_p10, E_p2, E_ph_borr, E_price_linear, E_rho_C, E_x1, E_x2, F_ltv_level,
  Om_m_diff, Om_pay_diff, borr_resource_costs, cpr_level, frac_pti_incentive, iss_per_loan,
  k_inv_cost, kap_collateral_term, kap_equity_term, kap_rate_term, kap_star, linear_err,
  log_F_ltv, log_F_pti, log_F_pti_cond, log_Lam_borr, log_Lam_borr_0_inv, log_Lam_borr_debt,
  log_Lam_borr_detrend, log_Lam_borr_nom, log_Lam_saver, log_Lam_saver_0_inv, log_Lam_saver_debt,
  log_Lam_saver_detrend, log_Lam_saver_nom, log_Om_m_borr, log_Om_m_saver, log_Om_pay_borr,
  log_Om_pay_saver, log_R, log_R_1, log_R_10, log_R_10_ann, log_R_1_ann, log_R_2,
  log_R_2_ann, log_R_ann, log_R_borr, log_R_new, log_R_new_100, log_R_real, log_R_taylor,
  log_R_til, log_R_unbdd, log_Rm, log_Rm_ann, log_Rm_spread, log_a, log_a_til, log_base_lim_ltv,
  log_base_lim_pti, log_base_lim_pti_denom, log_bet_borr, log_bet_saver, log_borr_rent,
  log_borr_rent_expense, log_borr_resources, log_borr_surplus, log_c, log_c_borr,
  log_c_hat_borr, log_c_hat_saver, log_c_saver, log_cpr, log_debt, log_debt_limit,
  log_debt_limit_ltv, log_debt_limit_pti, log_debt_mult, log_debt_new, log_debt_payment,
  log_debt_ratio, log_dispersion, log_dispersion_new, log_dltv_dh, log_dmbar_dn, log_dmpti_dn,
  log_e_bar, log_eps_g, log_eps_pol, log_euler_rhs_saver, log_g, log_h_borr, log_h_borr_new,
  log_h_borr_star, log_h_hat_borr, log_h_hat_borr_new, log_h_hat_saver, log_h_hat_saver_new,
  log_h_purch_borr, log_h_purch_saver, log_h_saver, log_h_saver_new, log_h_total,
  log_h_value, log_h_value_borr, log_h_value_saver, log_inflation_factor, log_inv_rate_borr,
  log_inv_rate_saver, log_labor_inc_borr, log_loan_to_borr_inc, log_lti, log_ltv,
  log_ltv_shadow_val, log_marg_util_borr, log_marg_util_saver, log_mc, log_mrs_borr,
  log_n, log_n_borr, log_n_hat_borr, log_n_hat_saver, log_n_saver, log_n_un_hat_borr,
  log_n_un_hat_saver, log_new_loan_size, log_non_am_share_t, log_nu_t, log_p1, log_p10,
  log_p2, log_p_star, log_pay_new, log_pay_ratio, log_pay_to_borr_inc, log_ph, log_ph_borr,
  log_ph_borr_implied, log_ph_borr_numerator, log_ph_saver, log_pi, log_pi_ann, log_pi_index,
  log_pi_star, log_price_rent_borr, log_profit, log_pti, log_q, log_q_star, log_refi_rate,
  log_refi_rate_unscaled, log_refi_rate_unscaled_implied, log_res_inv_borr, log_res_inv_saver,
  log_saver_rent, log_saver_rent_expense, log_spend_borr, log_spend_saver, log_taylor_infl_term,
  log_tot_collat_eff, log_tv_lim_both, log_tv_lim_ltv_tot, log_tv_lim_pti_tot, log_tv_tax_ins,
  log_tv_xi, log_uc_borr, log_uc_hat_borr, log_uc_hat_saver, log_uc_saver, log_uh_borr,
  log_uh_hat_borr, log_uh_hat_saver, log_uh_saver, log_vti, log_w_borr, log_w_borr_taxed,
  log_w_saver, log_w_saver_taxed, log_x1, log_x2, log_xc, log_xi_borr, log_xi_saver,
  log_y, log_y_implied, log_y_no_dispersion, ltv_gap, ltv_new_debt, mathcal_C, net_foreign_inflows,
  net_payment, new_issuance, pay, pti_incentive, pti_new_debt, q_ann_level, q_avg_ann_level,
  q_star_ann_level, res_inv_cost_borr, res_inv_cost_saver, res_inv_ratio, serv_costs,
  term_premium, term_premium_total, tot_transfer, yield_curve_slope, z_e_bar, z_e_bar_cond,
  z_kap;

varexo e_log_a_til, e_log_pi_star, e_log_tv_xi, e_term_premium;


// Parameters

H_hat_bar_borr = 8.02;
H_hat_bar_saver = 8.069;
H_to_inc_borr = 8.89;
H_to_inc_saver = 11.4;
alp_k = 0.0;
bet_bar_borr = 0.965383526122699;
bet_bar_saver = 0.9923005937398881;
chi_borr = 0.319;
coeff_0 = 2.5255130999894373;
coeff_m = 3.165013750068087;
cpr_bar = 0.12016985432251293;
del = 0.00493;
dispersion_max = 1.025;
dispersion_min = 1.0;
epsi = 6.0;
eta = 7.935;
eta_borr = 8.189650306003026;
eta_saver = 5.66151728892907;
frac_active = 0.25;
frequency = 4.0;
habit = 0.0;
init_avg_amort_diff = 0.000736342191821171;
kap_star_bar = 0.035;
log_H_hat_borr = 2.0026055262665956;
log_H_hat_saver = 2.2512917600599893;
log_R_cal = 0.01564978543912999;
log_R_spread = 0.01;
log_R_til_spread = 10000000000.0;
log_Rm_ann_bar = 0.07518631910003633;
log_a_bar = 1.0986122886682097;
log_debt_hat_bar = 2.125;
log_debt_limit_baseline = 0.6425243597741174;
log_debt_spread = 0.1;
log_dispersion_max = 0.05;
log_dispersion_min = 0.0;
log_dispersion_spread = 0.01;
log_g_bar = 0.0;
ltv_bar = 0.85;
mu_foreign_debt = 0.0;
mu_kap = 0.3479728257779681;
mu_log_a_til = 0.0;
mu_log_pi_star = 0.007920586844757655;
mu_log_tv_xi = 0.0;
mu_term_premium = 0.0;
mu_tv_tax_ins = 0.0028530296965698135;
n_std = 5.0;
n_std_endog = 10.0;
n_std_pc = 5.0;
non_am_share_nom_bar = 0.9956523941976516;
nu_bond = 0.975;
other_debt_frac = 0.08;
pay_spread = 0.01;
phi_h_adj = 20.0;
phi_pi = 1.5;
phi_y = 0.0;
pi_bar = 1.0079520376742455;
psi = 1.0;
pti_bar = 0.28;
q_coeff_bar = 284.6;
q_tax_ins_bar = 0.026175;
quiet = 1;
rho_adj = 1.0;
rho_foreign_debt = 0.95;
rho_log_a_til = 0.9641;
rho_log_pi_star = 0.994;
rho_log_tv_xi = 0.9;
rho_pol = 0.9;
rho_term_premium = 0.852;
scale = 1.0;
scale_final = 1.0;
servicing_costs = 0.0;
sig_adj = 1.0;
sig_e_inc = 0.411;
sig_foreign_debt = 0.001;
sig_kap = 0.15239735731402929;
sig_log_a_til = 0.0082;
sig_log_pi_star = 0.0015;
sig_log_tv_xi = 0.05;
sig_term_premium = 0.00079001906;
tau_inc = 0.204;
tp_offset_1 = 0.003201405050958735;
tp_offset_2 = 0.0;
varphi = 1.0;
xi_bar_borr = 0.25;
y_steady = 1.0;
zet = 0.75;
lam = (1.0 - zet) * (1.0 - bet_bar_saver * zet) / zet;
log_mc_bar = log((epsi - 1.0) / epsi);
nu_1 = 1.0 - 1.0 / (1.0 * frequency);
nu_2 = 1.0 - 1.0 / (2.0 * frequency);
nu_10 = 1.0 - 1.0 / (10.0 * frequency);
log_pi_bar = log(pi_bar);
log_R_real_bar = - log(bet_bar_saver) + psi * log_g_bar;
log_R_bar = log_R_real_bar + log_pi_bar;
varphi_inv = 1.0 / varphi;
g_bar = exp(log_g_bar);
bet_g_bar_saver = bet_bar_saver * exp((1.0 - psi) * log_g_bar);
bet_g_bar_nom_inv_saver = pi_bar / bet_g_bar_saver;
chi_saver = 1.0 - chi_borr;
bet_g_bar_borr = bet_bar_borr * exp((1.0 - psi) * log_g_bar);
bet_g_bar_nom_inv_borr = pi_bar / bet_g_bar_borr;
H_hat_saver = exp(log_H_hat_saver);
H_saver = chi_saver * H_hat_saver;
H_hat_borr = exp(log_H_hat_borr);
H_borr = chi_borr * H_hat_borr;
xi_bar_saver = xi_bar_borr;
non_am_share_bar = non_am_share_nom_bar;

// Equilibrium conditions

model;

log_pi_star = (1.0 - rho_log_pi_star) * mu_log_pi_star + rho_log_pi_star * log_pi_star(-1) + sig_log_pi_star * e_log_pi_star;
log_a_til = (1.0 - rho_log_a_til) * mu_log_a_til + rho_log_a_til * log_a_til(-1) + sig_log_a_til * e_log_a_til;
log_tv_xi = (1.0 - rho_log_tv_xi) * mu_log_tv_xi + rho_log_tv_xi * log_tv_xi(-1) + sig_log_tv_xi * e_log_tv_xi;
term_premium = (1.0 - rho_term_premium) * mu_term_premium + rho_term_premium * term_premium(-1) + sig_term_premium * e_term_premium;
log_pi = log_pi_index + log( (  (1.0 - (1.0 - zet) * ((exp(log_p_star)) ^ (1.0 - epsi))) / zet) ) / (epsi - 1.0);
log_R_1 = log(1.0 / exp(log_p1) + nu_1);
log_R_1_ann = 4.0 * log_R_1;
log_R_2 = log(1.0 / exp(log_p2) + nu_2);
log_R_2_ann = 4.0 * log_R_2;
log_R_10 = log(1.0 / exp(log_p10) + nu_10);
log_R_10_ann = 4.0 * log_R_10;
yield_curve_slope = log_R_10 - log_R_new;
log_Rm = log(exp(log_q_star) + exp(log_non_am_share_t));
log_Rm_ann = 4.0 * log_Rm;
log_Rm_spread = log_Rm - log_R_10;
q_star_ann_level = 4.0 * exp(log_q_star);
q_avg_ann_level = 4.0 * exp(log_pay_new - log_debt_new);
log_pi_ann = 4.0 * log_pi;
log_c = log(exp(log_c_borr) + exp(log_c_saver));
log_R_ann = 4.0 * log_R_new;
log_R_new_100 = 100.0 * log_R_new;
net_foreign_inflows = 0.0;
borr_resource_costs = 0.0;
tot_transfer = 0.0;
k_inv_cost = 0.0;
pti_incentive = exp(log_refi_rate) * exp(log_debt_mult) * exp(log_dmbar_dn);
frac_pti_incentive = pti_incentive / exp(log_w_borr);
log_eps_pol = 0.0;
log_taylor_infl_term = log_pi_star + phi_pi * (log_pi - log_pi_star);
log_R_taylor = log_R_real_bar + log_taylor_infl_term + (phi_y * (log(exp(log_y)))) + log_eps_pol;
log_R_unbdd = rho_pol * (log_R_til + log_pi_star) + (1.0 - rho_pol) * log_R_taylor;
log_R_new = log_R_unbdd;
log_eps_g = 0.0;
log_xc = 0.0;
res_inv_cost_saver = 0.5 * phi_h_adj * ((exp(log_inv_rate_saver) - del) ^ (2)) * exp(log_h_saver);
res_inv_cost_borr = 0.5 * phi_h_adj * ((exp(log_inv_rate_borr) - del) ^ (2)) * exp(log_h_borr);
log_price_rent_borr = log(exp(log_ph_borr) / exp(log_mrs_borr));
ltv_new_debt = exp(log_new_loan_size) / (exp(log_ph_borr) * exp(log_h_borr_new));
pti_new_debt = other_debt_frac + ((exp(log_q_star) + exp(log_tv_tax_ins)) * exp(log_new_loan_size) / exp(log_labor_inc_borr));
ltv_gap = new_issuance / exp(log_ph_borr);
iss_per_loan = exp(log_new_loan_size) - exp(log_nu_t) * exp(log_debt);
new_issuance = exp(log_refi_rate) * iss_per_loan;
net_payment = exp(log_debt_payment) - new_issuance;
serv_costs = servicing_costs * exp(log_debt);
log_debt_limit = log(exp(log_debt_limit_ltv) * exp(log_F_ltv) + exp(log_debt_limit_pti) * exp(log_F_pti_cond));
q_ann_level = 4.0 * exp(log_q);
term_premium_total = term_premium + tp_offset_1 + tp_offset_2;
Om_m_diff = exp(log_Om_m_saver) - exp(log_Om_m_borr);
Om_pay_diff = exp(log_Om_pay_saver) - exp(log_Om_pay_borr);
res_inv_ratio = (exp(log_inv_rate_borr) - del) * exp(log_h_borr) / exp(log_new_loan_size);
kap_equity_term = (1.0 - exp(log_Om_m_borr)) * (1.0 - exp(log_debt_ratio));
kap_rate_term = -exp(log_Om_pay_borr) * (exp(log_q_star) - exp(log_pay_ratio));
kap_collateral_term = -exp(log_ltv_shadow_val) * exp(log_ph_borr) * res_inv_ratio;
kap_star = (1.0 - exp(log_Om_m_borr)) * (1.0 - exp(log_debt_ratio)) - exp(log_Om_pay_borr) * (exp(log_q_star) - exp(log_pay_ratio))- exp(log_ltv_shadow_val) * exp(log_ph_borr) * res_inv_ratio;
z_kap = (kap_star - mu_kap) / sig_kap;
cpr_level = 1.0 - ((1.0 - exp(log_refi_rate)) ^ (frequency));
mathcal_C = exp(log_ltv_shadow_val);
z_e_bar = (log(exp(log_e_bar)) + 0.5 * ((sig_e_inc) ^ (2))) / sig_e_inc;
z_e_bar_cond = (log(exp(log_e_bar)) - 0.5 * ((sig_e_inc) ^ (2))) / sig_e_inc;
F_ltv_level = exp(log_F_ltv);
log_pay_new = log(exp(log_refi_rate) * exp(log_q_star) * exp(log_new_loan_size) + (1.0 - exp(log_refi_rate)) * exp(log_nu_t) * pay);
log_h_hat_borr = log(H_hat_borr);
log_mrs_borr = log(exp(log_uh_borr) / exp(log_uc_borr));
log_base_lim_ltv = log(ltv_bar * exp(log_ph_borr) * exp(log_h_borr_star));
log_h_saver = log(H_saver);
log_profit = log((1 - exp(log_mc)) * exp(log_y));
log_F_pti_cond = log(0.5 * (1.0 + erf(z_e_bar_cond / sqrt(2.0))));
log_n = log(exp(log_n_borr) + exp(log_n_saver));
log_q = log(pay / exp(log_debt));
log_h_purch_borr = log(exp(log_ph_borr) * exp(log_res_inv_borr));
log_uc_hat_saver = log((1.0/exp(log_c_hat_saver)));
log_marg_util_saver = log_uc_saver;
log_w_saver_taxed = log((1 - tau_inc) * exp(log_w_saver));
log_uh_saver = log(exp(log_uh_hat_saver) / chi_saver);
log_tv_lim_both = log(1.0);
log_ph_saver = log_ph_borr;
log_new_loan_size = log_debt_limit;
log_res_inv_borr = log(exp(log_inv_rate_borr) * exp(log_h_borr));
log_p_star = log(epsi * exp(log_x1) / ((epsi - 1.0) * exp(log_x2)));
log_cpr = log_refi_rate_unscaled;
log_uh_borr = log(exp(log_uh_hat_borr) / chi_borr);
log_bet_borr = log(bet_bar_borr);
log_Lam_borr_nom = log(exp(log_Lam_borr_detrend) / (exp(log_pi) * exp(log_g)));
log_debt_ratio = log(exp(log_nu_t) * exp(log_debt) / exp(log_new_loan_size));
log_h_hat_borr_new = log(exp(log_h_borr_new) / chi_borr);
log_h_hat_saver_new = log(exp(log_h_saver_new) / chi_saver);
log_borr_rent_expense = log(exp(log_borr_rent) * exp(log_h_hat_borr));
log_n_saver = log(chi_saver * exp(log_n_hat_saver));
log_n_un_hat_saver = log((((exp(log_n_hat_saver)) ^ (varphi))*eta_saver));
log_h_total = log(exp(log_h_borr) + exp(log_h_saver));
log_h_value = log(exp(log_ph) * exp(log_h_total));
log_marg_util_borr = log_uc_borr;
log_Lam_saver = log(exp(log_Lam_saver_detrend) / exp(log_g));
log_debt_mult = log(1.0 - (exp(log_Om_m_borr) + exp(log_q_star) * exp(log_Om_pay_borr)));
log_h_borr = log(H_borr);
log_F_pti = log(0.5 * (1.0 + erf(z_e_bar / sqrt(2.0))));
log_h_borr_new = log((1.0 - del + exp(log_inv_rate_borr)) * exp(log_h_borr));
log_Lam_borr = log(exp(log_Lam_borr_detrend) / exp(log_g));
log_n_un_hat_borr = log((((exp(log_n_hat_borr)) ^ (varphi))*eta_borr));
log_tv_lim_ltv_tot = log_tv_lim_both;
log_tv_tax_ins = log(mu_tv_tax_ins);
log_ltv = log(exp(log_debt_new) / (exp(log_ph_borr) * exp(log_h_borr_new)));
log_Lam_saver_debt = log_Lam_saver_nom;
log_base_lim_pti = log(pti_bar * exp(log_labor_inc_borr) / exp(log_base_lim_pti_denom));
log_uc_saver = log(exp(log_uc_hat_saver) / chi_saver);
log_debt_limit_pti = log(exp(log_tv_lim_pti_tot) * exp(log_base_lim_pti));
log_pay_ratio = log(exp(log_nu_t) * pay / exp(log_new_loan_size));
log_refi_rate_unscaled_implied = log(1.0 / (1.0 + exp(-z_kap)));
log_w_saver = log(exp(log_mc) * (1.0 - alp_k) * (exp(log_y_no_dispersion) / exp(log_n)));
log_dispersion_new = log(((1.0 - zet) * ((exp(log_p_star)) ^ (-epsi)) + zet * ((exp(log_pi) / exp(log_pi_index)) ^ (epsi)) * exp(log_dispersion)));
log_R_borr = log_R_new;
log_debt_limit_ltv = log(exp(log_tv_lim_ltv_tot) * exp(log_base_lim_ltv));
log_tv_lim_pti_tot = log_tv_lim_both;
log_saver_rent_expense = log(exp(log_saver_rent) * exp(log_h_hat_saver));
log_g = log(exp(log_g_bar + log_xc + log_eps_g));
log_pti = log(exp(log_pay_new) / exp(log_y));
log_inv_rate_borr = log(del);
log_e_bar = log(exp(log_debt_limit_ltv) / exp(log_debt_limit_pti));
log_q_star = log(term_premium_total + ((1.0 - exp(log_Om_m_saver)) / exp(log_Om_pay_saver)));
log_c_saver = log(chi_saver * exp(log_c_hat_saver));
log_inflation_factor = log(1.0 / exp(log_pi));
log_ltv_shadow_val = log(exp(log_debt_mult) * exp(log_F_ltv) * exp(log_dltv_dh));
log_bet_saver = log(bet_bar_saver);
log_uh_hat_saver = log(exp(log_xi_saver)/exp(log_h_hat_saver_new));
log_n_borr = log(chi_borr * exp(log_n_hat_borr));
log_debt_new = log(exp(log_nu_t) * exp(log_debt) + new_issuance);
log_F_ltv = log(1.0 - exp(log_F_pti));
log_h_saver_new = log((1.0 - del + exp(log_inv_rate_saver)) * exp(log_h_saver));
log_h_value_borr = log(exp(log_ph_borr) * exp(log_h_borr_new));
log_borr_resources = log(exp(log_labor_inc_borr) - net_payment + tot_transfer - exp(log_h_purch_borr) - borr_resource_costs);
log_xi_saver = log(exp(log_tv_xi) * xi_bar_saver);
log_debt_payment = log(pay * exp(log_inflation_factor) / exp(log_g));
log_dmbar_dn = log(exp(log_dmpti_dn) * exp(log_F_pti_cond));
log_uc_hat_borr = log((1.0/exp(log_c_hat_borr)));
log_pay_to_borr_inc = log(exp(log_pay_new) / exp(log_labor_inc_borr));
log_borr_rent = log(exp(log_uh_borr) / exp(log_uc_borr));
log_y_no_dispersion = log(exp(log_a) * exp(log_n));
log_saver_rent = log(exp(log_uh_saver) / exp(log_uc_saver));
log_Lam_borr_detrend = log(exp(log_marg_util_borr) * ((exp(log_g)) ^ (1.0 - psi)));
log_borr_surplus = log(1.0  - exp(log_R_borr) * exp(log_Om_m_borr));
log_lti = log(exp(log_debt_new) / exp(log_y));
log_labor_inc_borr = log(exp(log_w_borr) * exp(log_n_borr));
log_c_borr = log(chi_borr * exp(log_c_hat_borr));
log_xi_borr = log(exp(log_tv_xi) * xi_bar_borr);
log_refi_rate = log(exp(log_cpr) / frequency);
log_dmpti_dn = log(exp(log_debt_limit_pti) / exp(log_n_borr));
log_y = log(exp(log_c) + exp(log_res_inv_saver) + exp(log_res_inv_borr) + res_inv_cost_saver + res_inv_cost_borr + k_inv_cost + serv_costs);
log_Lam_borr_debt = log_Lam_borr_nom;
log_w_borr_taxed = log((1 - tau_inc) * exp(log_w_borr));
log_res_inv_saver = log(exp(log_inv_rate_saver) * exp(log_h_saver));
log_Lam_saver_nom = log(exp(log_Lam_saver_detrend) / (exp(log_pi) * exp(log_g)));
log_spend_saver = log(exp(log_c_saver) + exp(log_h_purch_saver));
log_spend_borr = log(exp(log_c_borr) + exp(log_h_purch_borr));
log_w_borr = log(exp(log_mc) * (1.0 - alp_k) * (exp(log_y_no_dispersion) / exp(log_n)));
log_h_borr_star = log((exp(log_res_inv_borr) - del * exp(log_h_borr)) / exp(log_refi_rate) + exp(log_h_borr));
log_non_am_share_t = log(non_am_share_bar);
log_loan_to_borr_inc = log(exp(log_debt_new) / exp(log_labor_inc_borr));
log_uh_hat_borr = log(exp(log_xi_borr)/exp(log_h_hat_borr_new));
log_a = log(exp(log_a_bar + log_a_til));
log_Lam_saver_detrend = log(exp(log_marg_util_saver) * ((exp(log_g)) ^ (1.0 - psi)));
log_dltv_dh = log(exp(log_tv_lim_ltv_tot) * ltv_bar);
log_h_hat_saver = log(H_hat_saver);
log_inv_rate_saver = log(del);
log_ph = log((exp(log_ph_borr) * exp(log_h_borr) + exp(log_ph_saver) * exp(log_h_saver)) / exp(log_h_total));
log_h_purch_saver = log(exp(log_ph_saver) * exp(log_res_inv_saver));
log_y_implied = log(exp(log_y_no_dispersion) / exp(log_dispersion));
log_h_value_saver = log(exp(log_ph_saver) * exp(log_h_saver_new));
log_nu_t = log(exp(log_non_am_share_t) * exp(log_inflation_factor) / exp(log_g));
log_uc_borr = log(exp(log_uc_hat_borr) / chi_borr);
log_pi_index = log(pi_bar);
log_vti = log(exp(log_ph) * (exp(log_h_borr) + exp(log_h_saver)) / exp(log_y));
log_base_lim_pti_denom = log((exp(log_q_star) + exp(log_tv_tax_ins)));
linear_err = 100.0 * (lam * (log(exp(log_mc)) - log_mc_bar) + exp(log_bet_saver) * E_price_linear - (log_pi - log_pi_bar));
log_R_real = log_R_new - E_log_pi;
log_ph_borr_implied = log(exp(log_ph_borr_numerator) / (1.0 - exp(log_ltv_shadow_val)));
log_euler_rhs_saver = log(chi_saver * exp(log_bet_saver) * exp(log_R_new) * E_euler_saver);
log_Lam_borr_0_inv = log(exp(log_marg_util_borr) / exp(log_bet_borr));
log_ph_borr_numerator = log(E_ph_borr / exp(log_Lam_borr_0_inv));
log_tot_collat_eff = log(E_rho_C / (1.0 - mathcal_C));
log_Lam_saver_0_inv = log(exp(log_marg_util_saver) / exp(log_bet_saver));
log_R_til = log_R_new(-1) - log_pi_star(-1);
log_R = log_R_new(-1);
pay = exp(log_pay_new(-1));
log_debt = log((exp(log_debt_new(-1))));
log_dispersion = log_dispersion_new(-1);
E_x1 = zet * exp(log_Lam_saver(+1)) * ((exp(log_pi(+1)) / exp(log_pi_index(+1))) ^ (epsi)) * exp(log_x1(+1));
E_x2 = zet * exp(log_Lam_saver(+1)) * ((exp(log_pi(+1)) / exp(log_pi_index(+1))) ^ (epsi - 1.0)) * exp(log_x2(+1));
E_price_linear = log_pi(+1) - log_pi_bar;
E_p1 = exp(log_Lam_saver_nom(+1)) * (1.0 + nu_1 * exp(log_p1(+1)));
E_p2 = exp(log_Lam_saver_nom(+1)) * (1.0 + nu_2 * exp(log_p2(+1)));
E_p10 = exp(log_Lam_saver_nom(+1)) * (1.0 + nu_10 * exp(log_p10(+1)));
E_euler_saver = exp(log_Lam_saver_nom(+1));
E_log_pi = log_pi(+1);
E_ph_borr = exp(log_Lam_borr_detrend(+1)) * (exp(log_mrs_borr(+1)) + exp(log_ph_borr(+1)) * (1.0 - del - (1.0 - exp(log_refi_rate(+1))) * exp(log_ltv_shadow_val(+1))));
E_Om_m_borr = exp(log_Lam_borr_debt(+1)) * ((1.0 - exp(log_non_am_share_t(+1))) * tau_inc + exp(log_non_am_share_t(+1)) * (exp(log_refi_rate(+1)) + (1.0 - exp(log_refi_rate(+1))) * exp(log_Om_m_borr(+1))));
E_Om_pay_borr = exp(log_Lam_borr_debt(+1)) * (1.0 - tau_inc + exp(log_non_am_share_t(+1)) * (1.0 - exp(log_refi_rate(+1))) * exp(log_Om_pay_borr(+1)));
E_Om_m_saver = exp(log_Lam_saver_debt(+1)) * (-servicing_costs + exp(log_non_am_share_t(+1)) * (exp(log_refi_rate(+1)) + (1.0 - exp(log_refi_rate(+1))) * exp(log_Om_m_saver(+1))));
E_Om_pay_saver = exp(log_Lam_saver_debt(+1)) * (1.0 + exp(log_non_am_share_t(+1)) * (1.0 - exp(log_refi_rate(+1))) * exp(log_Om_pay_saver(+1)));
E_rho_C = 1.0 - (1.0 - exp(log_refi_rate(+1))) * mathcal_C(+1);
log(exp(log_y) * exp(log_mc) + E_x1 / exp(log_Lam_saver_0_inv)) - log_x1 = 0.0;
log(exp(log_y) + E_x2 / exp(log_Lam_saver_0_inv)) - log_x2 = 0.0;
log_Lam_saver_0_inv - (log_R_new + log(E_euler_saver)) = 0.0;
log_borr_resources - log_c_borr = 0.0;
log_ph_borr_implied - log_ph_borr = 0.0;
log(E_Om_m_borr / exp(log_Lam_borr_0_inv)) - log_Om_m_borr = 0.0;
log(E_Om_pay_borr / exp(log_Lam_borr_0_inv)) - log_Om_pay_borr = 0.0;
log(E_Om_m_saver / exp(log_Lam_saver_0_inv)) - log_Om_m_saver = 0.0;
log(E_Om_pay_saver / exp(log_Lam_saver_0_inv)) - log_Om_pay_saver = 0.0;
log_refi_rate_unscaled - log(exp(log_refi_rate_unscaled_implied)) = 0.0;
log(exp(log_Lam_saver_0_inv) * exp(log_p2)) - log(E_p2) = 0.0;
log(exp(log_Lam_saver_0_inv) * exp(log_p1)) - log(E_p1) = 0.0;
log(exp(log_w_borr_taxed) + pti_incentive) - log(exp(log_n_un_hat_borr) / exp(log_uc_hat_borr)) = 0.0;
log(exp(log_w_saver_taxed)) - log(exp(log_n_un_hat_saver) / exp(log_uc_hat_saver)) = 0.0;
log_y - log_y_implied = 0.0;
log(exp(log_Lam_saver_0_inv) * exp(log_p10)) - log(E_p10) = 0.0;

end;

initval;

log_pi_star = mu_log_pi_star;
log_a_til = mu_log_a_til;
log_tv_xi = mu_log_tv_xi;
term_premium = mu_term_premium;
log_dispersion = 9.96700451955388e-14;
log_R_til = 0.007729199714958992;
log_R = 0.01564984251854685;
pay = 0.03376964299005051;
log_debt = 0.3701664244768165;
log_x1 = 1.1811363234571108;
log_x2 = 1.3634580491496189;
log_p1 = 1.3251129338536558;
log_p2 = 1.9606070225359769;
log_p10 = 3.1997365883657536;
log_c_hat_saver = 0.05305499857349674;
log_c_hat_borr = -0.29145753494001125;
log_n_hat_saver = -1.0986122886681098;
log_mc = -0.18232156187830292;
log_n_hat_borr = -1.0986122886681098;
log_ph_borr = 1.3847513022449625e-23;
log_Om_m_borr = -0.8080787305755939;
log_Om_pay_borr = 2.2276240620662726;
log_Om_m_saver = -0.43090594812876803;
log_Om_pay_saver = 2.8564191747604553;
log_refi_rate_unscaled = -1.896673660982237;
E_x1 = 3.4027771119934287;
E_x2 = 4.083333453950957;
E_price_linear = -5.629954948592475e-08;
E_p1 = 5.2802855227246495;
E_p2 = 9.968940018416765;
E_p10 = 34.41883098786671;
E_euler_saver = 1.3815656653278314;
E_log_pi = 0.00792058650403837;
E_ph_borr = 3.4235437595536626;
E_Om_m_borr = 1.937062865778785;
E_Om_pay_borr = 40.32112929861905;
E_Om_m_saver = 0.9120698431372835;
E_Om_pay_saver = 24.41716609533939;
E_rho_C = 0.7957123114967821;
log_tv_tax_ins = log(mu_tv_tax_ins);
log_p_star = log(epsi * exp(log_x1) / ((epsi - 1.0) * exp(log_x2)));
log_xc = 0.0;
log_c_borr = log(chi_borr * exp(log_c_hat_borr));
log_n_borr = log(chi_borr * exp(log_n_hat_borr));
log_n_saver = log(chi_saver * exp(log_n_hat_saver));
log_n = log(exp(log_n_borr) + exp(log_n_saver));
term_premium_total = term_premium + tp_offset_1 + tp_offset_2;
log_q_star = log(term_premium_total + ((1.0 - exp(log_Om_m_saver)) / exp(log_Om_pay_saver)));
log_debt_mult = log(1.0 - (exp(log_Om_m_borr) + exp(log_q_star) * exp(log_Om_pay_borr)));
log_base_lim_pti_denom = log((exp(log_q_star) + exp(log_tv_tax_ins)));
q_star_ann_level = 4.0 * exp(log_q_star);
log_uc_hat_saver = log((1.0/exp(log_c_hat_saver)));
log_uc_saver = log(exp(log_uc_hat_saver) / chi_saver);
log_marg_util_saver = log_uc_saver;
serv_costs = servicing_costs * exp(log_debt);
Om_pay_diff = exp(log_Om_pay_saver) - exp(log_Om_pay_borr);
log_bet_borr = log(bet_bar_borr);
net_foreign_inflows = 0.0;
tot_transfer = 0.0;
log_n_un_hat_borr = log((((exp(log_n_hat_borr)) ^ (varphi))*eta_borr));
log_tv_lim_both = log(1.0);
log_tv_lim_ltv_tot = log_tv_lim_both;
log_dltv_dh = log(exp(log_tv_lim_ltv_tot) * ltv_bar);
log_tv_lim_pti_tot = log_tv_lim_both;
log_cpr = log_refi_rate_unscaled;
log_refi_rate = log(exp(log_cpr) / frequency);
cpr_level = 1.0 - ((1.0 - exp(log_refi_rate)) ^ (frequency));
log_n_un_hat_saver = log((((exp(log_n_hat_saver)) ^ (varphi))*eta_saver));
log_uc_hat_borr = log((1.0/exp(log_c_hat_borr)));
log_uc_borr = log(exp(log_uc_hat_borr) / chi_borr);
log_marg_util_borr = log_uc_borr;
log_Lam_borr_0_inv = log(exp(log_marg_util_borr) / exp(log_bet_borr));
log_ph_borr_numerator = log(E_ph_borr / exp(log_Lam_borr_0_inv));
Om_m_diff = exp(log_Om_m_saver) - exp(log_Om_m_borr);
log_xi_borr = log(exp(log_tv_xi) * xi_bar_borr);
log_h_borr = log(H_borr);
k_inv_cost = 0.0;
log_h_saver = log(H_saver);
log_h_total = log(exp(log_h_borr) + exp(log_h_saver));
log_a = log(exp(log_a_bar + log_a_til));
log_y_no_dispersion = log(exp(log_a) * exp(log_n));
log_y_implied = log(exp(log_y_no_dispersion) / exp(log_dispersion));
log_w_borr = log(exp(log_mc) * (1.0 - alp_k) * (exp(log_y_no_dispersion) / exp(log_n)));
log_labor_inc_borr = log(exp(log_w_borr) * exp(log_n_borr));
log_base_lim_pti = log(pti_bar * exp(log_labor_inc_borr) / exp(log_base_lim_pti_denom));
log_debt_limit_pti = log(exp(log_tv_lim_pti_tot) * exp(log_base_lim_pti));
log_dmpti_dn = log(exp(log_debt_limit_pti) / exp(log_n_borr));
log_w_borr_taxed = log((1 - tau_inc) * exp(log_w_borr));
log_w_saver = log(exp(log_mc) * (1.0 - alp_k) * (exp(log_y_no_dispersion) / exp(log_n)));
log_w_saver_taxed = log((1 - tau_inc) * exp(log_w_saver));
log_R_2 = log(1.0 / exp(log_p2) + nu_2);
log_R_2_ann = 4.0 * log_R_2;
log_h_hat_saver = log(H_hat_saver);
log_ph_saver = log_ph_borr;
log_ph = log((exp(log_ph_borr) * exp(log_h_borr) + exp(log_ph_saver) * exp(log_h_saver)) / exp(log_h_total));
log_h_value = log(exp(log_ph) * exp(log_h_total));
log_eps_pol = 0.0;
log_eps_g = 0.0;
log_g = log(exp(log_g_bar + log_xc + log_eps_g));
log_Lam_borr_detrend = log(exp(log_marg_util_borr) * ((exp(log_g)) ^ (1.0 - psi)));
log_Lam_borr = log(exp(log_Lam_borr_detrend) / exp(log_g));
log_Lam_saver_detrend = log(exp(log_marg_util_saver) * ((exp(log_g)) ^ (1.0 - psi)));
log_Lam_saver = log(exp(log_Lam_saver_detrend) / exp(log_g));
log_q = log(pay / exp(log_debt));
q_ann_level = 4.0 * exp(log_q);
borr_resource_costs = 0.0;
log_inv_rate_saver = log(del);
log_h_saver_new = log((1.0 - del + exp(log_inv_rate_saver)) * exp(log_h_saver));
log_h_value_saver = log(exp(log_ph_saver) * exp(log_h_saver_new));
log_h_hat_saver_new = log(exp(log_h_saver_new) / chi_saver);
log_res_inv_saver = log(exp(log_inv_rate_saver) * exp(log_h_saver));
log_h_purch_saver = log(exp(log_ph_saver) * exp(log_res_inv_saver));
res_inv_cost_saver = 0.5 * phi_h_adj * ((exp(log_inv_rate_saver) - del) ^ (2)) * exp(log_h_saver);
log_R_10 = log(1.0 / exp(log_p10) + nu_10);
log_R_10_ann = 4.0 * log_R_10;
log_R_1 = log(1.0 / exp(log_p1) + nu_1);
log_R_1_ann = 4.0 * log_R_1;
log_non_am_share_t = log(non_am_share_bar);
log_Rm = log(exp(log_q_star) + exp(log_non_am_share_t));
log_Rm_ann = 4.0 * log_Rm;
log_Rm_spread = log_Rm - log_R_10;
log_pi_index = log(pi_bar);
log_pi = log_pi_index + log( (  (1.0 - (1.0 - zet) * ((exp(log_p_star)) ^ (1.0 - epsi))) / zet) ) / (epsi - 1.0);
log_inflation_factor = log(1.0 / exp(log_pi));
log_debt_payment = log(pay * exp(log_inflation_factor) / exp(log_g));
log_nu_t = log(exp(log_non_am_share_t) * exp(log_inflation_factor) / exp(log_g));
log_Lam_saver_nom = log(exp(log_Lam_saver_detrend) / (exp(log_pi) * exp(log_g)));
log_Lam_saver_debt = log_Lam_saver_nom;
log_taylor_infl_term = log_pi_star + phi_pi * (log_pi - log_pi_star);
log_dispersion_new = log(((1.0 - zet) * ((exp(log_p_star)) ^ (-epsi)) + zet * ((exp(log_pi) / exp(log_pi_index)) ^ (epsi)) * exp(log_dispersion)));
log_pi_ann = 4.0 * log_pi;
log_Lam_borr_nom = log(exp(log_Lam_borr_detrend) / (exp(log_pi) * exp(log_g)));
log_Lam_borr_debt = log_Lam_borr_nom;
log_xi_saver = log(exp(log_tv_xi) * xi_bar_saver);
log_uh_hat_saver = log(exp(log_xi_saver)/exp(log_h_hat_saver_new));
log_uh_saver = log(exp(log_uh_hat_saver) / chi_saver);
log_saver_rent = log(exp(log_uh_saver) / exp(log_uc_saver));
log_saver_rent_expense = log(exp(log_saver_rent) * exp(log_h_hat_saver));
log_inv_rate_borr = log(del);
log_h_borr_new = log((1.0 - del + exp(log_inv_rate_borr)) * exp(log_h_borr));
log_h_hat_borr_new = log(exp(log_h_borr_new) / chi_borr);
log_uh_hat_borr = log(exp(log_xi_borr)/exp(log_h_hat_borr_new));
log_uh_borr = log(exp(log_uh_hat_borr) / chi_borr);
log_borr_rent = log(exp(log_uh_borr) / exp(log_uc_borr));
log_mrs_borr = log(exp(log_uh_borr) / exp(log_uc_borr));
log_price_rent_borr = log(exp(log_ph_borr) / exp(log_mrs_borr));
log_h_value_borr = log(exp(log_ph_borr) * exp(log_h_borr_new));
res_inv_cost_borr = 0.5 * phi_h_adj * ((exp(log_inv_rate_borr) - del) ^ (2)) * exp(log_h_borr);
log_res_inv_borr = log(exp(log_inv_rate_borr) * exp(log_h_borr));
log_h_purch_borr = log(exp(log_ph_borr) * exp(log_res_inv_borr));
log_spend_borr = log(exp(log_c_borr) + exp(log_h_purch_borr));
log_h_borr_star = log((exp(log_res_inv_borr) - del * exp(log_h_borr)) / exp(log_refi_rate) + exp(log_h_borr));
log_base_lim_ltv = log(ltv_bar * exp(log_ph_borr) * exp(log_h_borr_star));
log_debt_limit_ltv = log(exp(log_tv_lim_ltv_tot) * exp(log_base_lim_ltv));
log_e_bar = log(exp(log_debt_limit_ltv) / exp(log_debt_limit_pti));
z_e_bar_cond = (log(exp(log_e_bar)) - 0.5 * ((sig_e_inc) ^ (2))) / sig_e_inc;
log_F_pti_cond = log(0.5 * (1.0 + erf(z_e_bar_cond / sqrt(2.0))));
log_dmbar_dn = log(exp(log_dmpti_dn) * exp(log_F_pti_cond));
pti_incentive = exp(log_refi_rate) * exp(log_debt_mult) * exp(log_dmbar_dn);
frac_pti_incentive = pti_incentive / exp(log_w_borr);
z_e_bar = (log(exp(log_e_bar)) + 0.5 * ((sig_e_inc) ^ (2))) / sig_e_inc;
log_F_pti = log(0.5 * (1.0 + erf(z_e_bar / sqrt(2.0))));
log_F_ltv = log(1.0 - exp(log_F_pti));
F_ltv_level = exp(log_F_ltv);
log_debt_limit = log(exp(log_debt_limit_ltv) * exp(log_F_ltv) + exp(log_debt_limit_pti) * exp(log_F_pti_cond));
log_new_loan_size = log_debt_limit;
iss_per_loan = exp(log_new_loan_size) - exp(log_nu_t) * exp(log_debt);
new_issuance = exp(log_refi_rate) * iss_per_loan;
net_payment = exp(log_debt_payment) - new_issuance;
log_borr_resources = log(exp(log_labor_inc_borr) - net_payment + tot_transfer - exp(log_h_purch_borr) - borr_resource_costs);
log_debt_new = log(exp(log_nu_t) * exp(log_debt) + new_issuance);
log_loan_to_borr_inc = log(exp(log_debt_new) / exp(log_labor_inc_borr));
log_ltv = log(exp(log_debt_new) / (exp(log_ph_borr) * exp(log_h_borr_new)));
ltv_gap = new_issuance / exp(log_ph_borr);
log_pay_new = log(exp(log_refi_rate) * exp(log_q_star) * exp(log_new_loan_size) + (1.0 - exp(log_refi_rate)) * exp(log_nu_t) * pay);
log_pay_to_borr_inc = log(exp(log_pay_new) / exp(log_labor_inc_borr));
q_avg_ann_level = 4.0 * exp(log_pay_new - log_debt_new);
log_pay_ratio = log(exp(log_nu_t) * pay / exp(log_new_loan_size));
kap_rate_term = -exp(log_Om_pay_borr) * (exp(log_q_star) - exp(log_pay_ratio));
res_inv_ratio = (exp(log_inv_rate_borr) - del) * exp(log_h_borr) / exp(log_new_loan_size);
log_debt_ratio = log(exp(log_nu_t) * exp(log_debt) / exp(log_new_loan_size));
kap_equity_term = (1.0 - exp(log_Om_m_borr)) * (1.0 - exp(log_debt_ratio));
pti_new_debt = other_debt_frac + ((exp(log_q_star) + exp(log_tv_tax_ins)) * exp(log_new_loan_size) / exp(log_labor_inc_borr));
ltv_new_debt = exp(log_new_loan_size) / (exp(log_ph_borr) * exp(log_h_borr_new));
log_ltv_shadow_val = log(exp(log_debt_mult) * exp(log_F_ltv) * exp(log_dltv_dh));
kap_star = (1.0 - exp(log_Om_m_borr)) * (1.0 - exp(log_debt_ratio)) - exp(log_Om_pay_borr) * (exp(log_q_star) - exp(log_pay_ratio))- exp(log_ltv_shadow_val) * exp(log_ph_borr) * res_inv_ratio;
z_kap = (kap_star - mu_kap) / sig_kap;
log_refi_rate_unscaled_implied = log(1.0 / (1.0 + exp(-z_kap)));
mathcal_C = exp(log_ltv_shadow_val);
log_tot_collat_eff = log(E_rho_C / (1.0 - mathcal_C));
kap_collateral_term = -exp(log_ltv_shadow_val) * exp(log_ph_borr) * res_inv_ratio;
log_ph_borr_implied = log(exp(log_ph_borr_numerator) / (1.0 - exp(log_ltv_shadow_val)));
log_c_saver = log(chi_saver * exp(log_c_hat_saver));
log_spend_saver = log(exp(log_c_saver) + exp(log_h_purch_saver));
log_c = log(exp(log_c_borr) + exp(log_c_saver));
log_y = log(exp(log_c) + exp(log_res_inv_saver) + exp(log_res_inv_borr) + res_inv_cost_saver + res_inv_cost_borr + k_inv_cost + serv_costs);
log_R_taylor = log_R_real_bar + log_taylor_infl_term + (phi_y * (log(exp(log_y)))) + log_eps_pol;
log_R_unbdd = rho_pol * (log_R_til + log_pi_star) + (1.0 - rho_pol) * log_R_taylor;
log_R_new = log_R_unbdd;
log_R_ann = 4.0 * log_R_new;
yield_curve_slope = log_R_10 - log_R_new;
log_R_borr = log_R_new;
log_borr_surplus = log(1.0  - exp(log_R_borr) * exp(log_Om_m_borr));
log_R_real = log_R_new - E_log_pi;
log_R_new_100 = 100.0 * log_R_new;
log_profit = log((1 - exp(log_mc)) * exp(log_y));
log_vti = log(exp(log_ph) * (exp(log_h_borr) + exp(log_h_saver)) / exp(log_y));
log_pti = log(exp(log_pay_new) / exp(log_y));
log_lti = log(exp(log_debt_new) / exp(log_y));
log_bet_saver = log(bet_bar_saver);
linear_err = 100.0 * (lam * (log(exp(log_mc)) - log_mc_bar) + exp(log_bet_saver) * E_price_linear - (log_pi - log_pi_bar));
log_Lam_saver_0_inv = log(exp(log_marg_util_saver) / exp(log_bet_saver));
log_euler_rhs_saver = log(chi_saver * exp(log_bet_saver) * exp(log_R_new) * E_euler_saver);
log_h_hat_borr = log(H_hat_borr);
log_borr_rent_expense = log(exp(log_borr_rent) * exp(log_h_hat_borr));

end;

shocks;

var e_log_pi_star; stderr 1;
var e_log_a_til; stderr 1;
var e_log_tv_xi; stderr 1;
var e_term_premium; stderr 1;

end;

steady;


stoch_simul(order=1) log_pi_star log_a_til log_tv_xi term_premium;
